const text: Record<string, string> = {
  "The prototype works.": "Прототип работает.",
  "Now make it hold up.": "Теперь сделайте его надёжным.",
  "ER11 is a compact product delivery team:": "ER11 — компактная команда продуктовой разработки:",
  "product direction and UX, production frontend, and backend delivery—coordinated as one production path.": "продуктовое направление и UX, frontend для продакшена и backend-разработка — единый путь к выпуску.",
  "Inspect selected work": "Смотреть выбранные работы",
  "Best fit: B2B tools with a working prototype": "Лучше всего: B2B-инструменты с работающим прототипом",
  "Prototype fragments": "Фрагменты прототипа",
  "Registered production proof": "Сведённое доказательство готовности",
  "Product / UX": "Продукт / UX",
  "Frontend": "Фронтенд",
  "Backend": "Бэкенд",
  "Three ownership layers. One production path.": "Три зоны ответственности. Один путь к релизу.",
  "Run press check": "Проверить сведение",
  "Ready — 03 layers queued": "Готово — 03 слоя в очереди",
  "Registered — 03 layers locked": "Сведено — 03 слоя закреплены",
  "Start a project": "Начать проект",
  "Continue on Upwork": "Продолжить на Upwork",
  "Back to Upwork": "Вернуться в Upwork",
  "Intro": "Начало",
  "Work": "Работы",
  "Risk": "Риски",
  "Scope": "Объём",
  "Team": "Команда",
  "Stack": "Стек",
  "Contact": "Контакт",
  "Page index": "Навигация по странице",
  "Landing page sections": "Разделы страницы",
  "ER11 — back to top": "ER11 — наверх",
  "Team register": "Реестр команды",
  "03 layers": "03 слоя",
  "Product": "Продукт",
  "One team": "Одна команда",
  "Experience clients can verify.": "Опыт, который можно проверить.",
  "Selected client and partner work published by Alexander Tishchenko, our Product / UX lead.": "Выбранные клиентские и партнёрские работы опубликованы Александром Тищенко, нашим лидом Product / UX.",
  "View the source portfolio": "Открыть исходное портфолио",
  "Sources are available in the Upwork conversation": "Источники доступны в переписке Upwork",
  "Selected client and partner experience": "Выбранный клиентский и партнёрский опыт",
  "Selected work, not borrowed claims.": "Выбранные работы, а не заимствованные заявления.",
  "These public examples belong to our Product / UX lead. Engineering proof is discussed against the scope, codebase, and release path of your project.": "Эти публичные примеры принадлежат нашему лиду Product / UX. Инженерные доказательства обсуждаем в контексте объёма, кодовой базы и пути релиза вашего проекта.",
  "Inspect project": "Открыть проект",
  "The gap is rarely “more code.” It is unresolved product risk.": "Проблема редко в «ещё большем коде». Обычно это неразрешённый продуктовый риск.",
  "Inspect the system between the visible interface and the release.": "Проверяем систему между видимым интерфейсом и релизом.",
  "Proof item": "Пункт проверки",
  "What we inspect": "Что проверяем",
  "Owner": "Ответственный",
  "Critical flows": "Критические сценарии",
  "Primary task, empty, loading, error, permission, and recovery states.": "Основная задача, пустые состояния, загрузка, ошибки, права доступа и восстановление.",
  "Frontend integrity": "Целостность фронтенда",
  "Architecture, responsive behavior, accessibility, performance, and maintainable state.": "Архитектура, адаптивность, доступность, производительность и поддерживаемое состояние.",
  "Backend reliability": "Надёжность бэкенда",
  "Data model, authorization, retries, observability, and operational failure modes.": "Модель данных, авторизация, повторы, наблюдаемость и рабочие отказы.",
  "Release path": "Путь к релизу",
  "Scope, acceptance criteria, quality checks, handoff, and the next informed decision.": "Объём, критерии приёмки, проверки качества, передача и следующее обоснованное решение.",
  "All three": "Все трое",
  "Choose the first proof, not the whole roadmap.": "Выберите первое доказательство, а не весь роадмап.",
  "Start with the smallest scope that can replace uncertainty with evidence.": "Начните с минимального объёма, который заменит неопределённость фактами.",
  "Diagnostic": "Диагностика",
  "Build": "Разработка",
  "Continue": "Продолжение",
  "Production Readiness Sprint": "Спринт готовности к продакшену",
  "Critical Flow to Production": "Критический сценарий в продакшен",
  "Product Continuity": "Непрерывность продукта",
  "Discuss this scope": "Обсудить этот объём",
  "Three accountable roles. One product path.": "Три ответственные роли. Один путь продукта.",
  "Accountable role": "Ответственная роль",
  "Verified attribution": "Проверенная атрибуция",
  "Flows, systems, and a handoff engineers can trust.": "Сценарии, системы и передача, которой инженеры доверяют.",
  "Typed interfaces with a production-ready delivery path.": "Типизированные интерфейсы с путём к продакшену.",
  "Fast services, durable data, and observable runtime behavior.": "Быстрые сервисы, надёжные данные и наблюдаемая работа системы.",
  "Technology register": "Реестр технологий",
  "Know the fit before the scope.": "Проверьте соответствие до определения объёма.",
  "Fit check": "Проверка соответствия",
  "Likely a fit": "Скорее подходим",
  "Probably not": "Скорее не подходим",
  "A working prototype.": "Работающий прототип.",
  "One critical flow to harden.": "Один критический сценарий для усиления.",
  "Senior disciplines working together.": "Senior-специалисты, работающие вместе.",
  "A pitch before product context.": "Питч без контекста продукта.",
  "Three isolated executors.": "Три изолированных исполнителя.",
  "A fixed bid before we inspect the critical flow.": "Фиксированная цена до проверки критического сценария.",
  "What clients ask before scope.": "Что клиенты спрашивают до определения объёма.",
  "Bring us the flow that cannot fail.": "Принесите нам сценарий, который не должен подвести.",
  "Your name": "Ваше имя",
  "Work email": "Рабочий email",
  "Product stage": "Стадия продукта",
  "Choose one": "Выберите вариант",
  "Working prototype": "Работающий прототип",
  "Existing product": "Существующий продукт",
  "New build": "Новая разработка",
  "What needs to hold up?": "Что должно стать надёжным?",
  "Compose enquiry": "Подготовить запрос",
  "Verified contact routes": "Проверенные каналы связи",
  "Privacy & form handling": "Приватность и обработка формы",
  "All work": "Все работы",
  "Project proof": "Доказательства по проекту",
  "Selected work": "Выбранные работы",
  "Discipline": "Дисциплина",
  "Proof type": "Тип доказательства",
  "Source state": "Статус источника",
  "Project record": "Карточка проекта",
  "Available evidence": "Доступные доказательства",
  "Next project /": "Следующий проект /",
  "Evidence boundary": "Граница доказательств",
  "Inspect the published source.": "Открыть опубликованный источник.",
  "Open case study": "Открыть кейс",
  "Open RePay": "Открыть RePay",
  "Open Behance case": "Открыть кейс Behance",
  "Lead operations desk": "Рабочее место для обработки лидов",
  "Interface work for a sales team handling lead queues, assignment, status tracking, and handoffs.": "Интерфейс для отдела продаж: очереди лидов, назначение ответственных, статусы и передача задач.",
  "Workflow architecture": "Архитектура сценариев",
  "Operational interface layouts": "Операционные макеты интерфейса",
  "Published case study": "Опубликованный кейс",
  "A sales operations interface organized around lead intake, ownership, and handoffs.": "Интерфейс продаж, построенный вокруг приёма лидов, ответственности и передачи задач.",
  "RePay": "RePay",
  "Interface work for a payment product covering public service information and a private management workspace.": "Интерфейс для платёжного продукта: публичная информация о сервисе и закрытое рабочее пространство управления.",
  "Product interface design": "Дизайн продуктового интерфейса",
  "Payment-related screens": "Экраны, связанные с платежами",
  "Public website": "Публичный сайт",
  "A payment product interface connecting public service information with private operations screens.": "Интерфейс платёжного продукта, соединяющий публичную информацию о сервисе с закрытыми операционными экранами.",
  "AGC Burya": "AGC Burya",
  "UI/UX collaboration for an agency website, including information structure, visual direction, and interface layouts.": "UI/UX-коллаборация для сайта агентства: информационная структура, визуальное направление и макеты интерфейса.",
  "Information structure": "Информационная структура",
  "Visual direction": "Визуальное направление",
  "Published Behance case": "Опубликованный кейс Behance",
  "An agency website collaboration shaped through information structure, visual direction, and final interface layouts.": "Совместная работа над сайтом агентства: информационная структура, визуальное направление и финальные макеты интерфейса.",
  "Lead work as an operating sequence": "Работа с лидами как операционная последовательность",
  "The case documents a B2B sales workspace for reviewing incoming leads, assigning ownership, recording status, and handing work between team members.": "Кейс показывает B2B-рабочее пространство продаж: просмотр входящих лидов, назначение ответственных, фиксация статусов и передача работы между участниками команды.",
  "Records, states, and follow-up actions": "Карточки, статусы и последующие действия",
  "The interface groups lead records with the status and follow-up information used during daily sales operations.": "Интерфейс объединяет карточки лидов со статусами и информацией для последующих действий в ежедневной работе продаж.",
  "Workflow and interface material": "Материалы по сценариям и интерфейсу",
  "The published case study contains workflow structure and interface layouts for the lead operations desk.": "В опубликованном кейсе есть структура сценариев и макеты интерфейса рабочего места для обработки лидов.",
  "Public information and private operations": "Публичная информация и закрытые операции",
  "The project covers a public-facing payment service website and a separate private management interface.": "Проект включает публичный сайт платёжного сервиса и отдельный закрытый интерфейс управления.",
  "Payment-related screens and controls": "Платёжные экраны и элементы управления",
  "The interface material organizes payment information, management actions, and operational states across the product surfaces.": "Материалы интерфейса организуют платёжную информацию, действия управления и операционные состояния на разных поверхностях продукта.",
  "A public reference and private screen set": "Публичный источник и набор закрытых экранов",
  "The recorded public source covers the service-facing part of the project; private interface work is described without exposing access details.": "Зафиксированный публичный источник показывает клиентскую часть проекта; закрытая интерфейсная работа описана без раскрытия деталей доступа.",
  "Structure and visual direction": "Структура и визуальное направление",
  "The agency website collaboration covers information structure, visual direction, and the preparation of interface layouts.": "Совместная работа над сайтом агентства включает информационную структуру, визуальное направление и подготовку макетов интерфейса.",
  "A consistent set of agency pages": "Единая система страниц агентства",
  "The interface work applies a shared visual language across the website's page structure and content areas.": "Работа над интерфейсом применяет единый визуальный язык к структуре страниц и контентным зонам сайта.",
  "Published UI/UX case material": "Опубликованные UI/UX-материалы кейса",
  "The Behance case presents the information structure, visual direction, and interface layouts prepared for the agency website.": "Кейс на Behance показывает информационную структуру, визуальное направление и макеты интерфейса для сайта агентства.",
};

const preserveWhitespace = (value: string, replacement: string) => {
  const leading = value.match(/^\s*/u)?.[0] ?? "";
  const trailing = value.match(/\s*$/u)?.[0] ?? "";
  return `${leading}${replacement}${trailing}`;
};

const translateText = () => {
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  nodes.forEach((node) => {
    const source = node.textContent ?? "";
    const key = source.trim();
    if (text[key]) node.textContent = preserveWhitespace(source, text[key]);
  });

  document.querySelectorAll<HTMLElement>("[aria-label], [alt], [placeholder]").forEach((element) => {
    (["aria-label", "alt", "placeholder"] as const).forEach((attribute) => {
      const value = element.getAttribute(attribute);
      if (value && text[value]) element.setAttribute(attribute, text[value]);
    });
  });

  document.querySelectorAll<HTMLAnchorElement>('a[href^="/projects/"], a[href^="/upwork/projects/"], a[href="/"], a[href="/upwork"]').forEach((link) => {
    const href = link.getAttribute("href");
    if (href && !href.startsWith("/ru")) link.setAttribute("href", `/ru${href}`);
  });
};

translateText();
